name: isolate_handler
description: Effortless isolates abstraction layer with support for inter-isolate communication.
version: 1.0.2
homepage: https://github.com/deakjahn/isolate_handler
documentation: https://github.com/deakjahn/isolate_handler/blob/0.2.0/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_isolate: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
